export const criptos = [
  { nome: 'Bitcoin', ticker: 'BTC' },
  { nome: 'Ethereum', ticker: 'ETH' },
  { nome: 'Solana', ticker: 'SOL' },
  { nome: 'Tether', ticker: 'USDT' },
  { nome: 'USD Coin', ticker: 'USDC' },
  { nome: 'XRP', ticker: 'XRP' },
  { nome: 'Tron', ticker: 'TRX' },
  { nome: 'Dogecoin', ticker: 'DOGE' },
  { nome: 'Cardano', ticker: 'ADA' },
  { nome: 'Wrapped Bitcoin', ticker: 'WBTC' },
  { nome: 'Hyperliquid', ticker: 'HYPE' },
  { nome: 'Bitcoin Cash', ticker: 'BCH' },
  { nome: 'Sui', ticker: 'SUI' },
  { nome: 'Chainlink', ticker: 'LINK' },
  { nome: 'Avalanche', ticker: 'AVAX' },
  { nome: 'Stellar', ticker: 'XLM' },
  { nome: 'Toncoin', ticker: 'TON' },
  { nome: 'Shiba Inu', ticker: 'SHIB' },
  { nome: 'Litecoin', ticker: 'LTC' },
  { nome: 'Hedera', ticker: 'HBAR' },
  { nome: 'Dai', ticker: 'DAI' },
  { nome: 'Polkadot', ticker: 'DOT' },
  { nome: 'Uniswap', ticker: 'UNI' },
  { nome: 'Pepe', ticker: 'PEPE' },
  { nome: 'Aave', ticker: 'AAVE' },
  { nome: 'Pi Network', ticker: 'PI' },
  { nome: 'Aptos', ticker: 'APT' },
  { nome: 'Bittensor', ticker: 'TAO' },
  { nome: 'Render Token', ticker: 'RNDR' },
  { nome: 'Near', ticker: 'NEAR' },
  { nome: 'Internet Computer', ticker: 'ICP' },
  { nome: 'Ethereum Classic', ticker: 'ETC' },
  { nome: 'Ondo', ticker: 'ONDO' },
  { nome: 'USD1', ticker: 'USD1' },
  { nome: 'Fantom', ticker: 'FTM' },
  { nome: 'Mantle', ticker: 'MNT' },
  { nome: 'Polygon', ticker: 'POL' },
  { nome: 'Official Trump', ticker: 'TRUMP' },
  { nome: 'Sky', ticker: 'SKY' },
  { nome: 'Arbitrum', ticker: 'ARB' },
  { nome: 'Algorand', ticker: 'ALGO' },
  { nome: 'Render', ticker: 'RENDER' },
  { nome: 'Artificial Superintelligence Alliance', ticker: 'FET' },
  { nome: 'Cosmos', ticker: 'ATOM' },
  { nome: 'Ethena', ticker: 'ENA' },
  { nome: 'Sei', ticker: 'SEI' },
  { nome: 'Filecoin', ticker: 'FIL' },
  { nome: 'Worldcoin', ticker: 'WLD' },
  { nome: 'Jupiter', ticker: 'JUP' },
  { nome: 'Quant', ticker: 'QNT' },
  { nome: 'Flare', ticker: 'FLR' },
  { nome: 'Bonk', ticker: 'BONK' },
  { nome: 'Fartcoin', ticker: 'FARTCOIN' },
  { nome: 'SPX6900', ticker: 'SPX' },
  { nome: 'Injective', ticker: 'INJ' },
  { nome: 'Stacks', ticker: 'STX' },
  { nome: 'Virtuals', ticker: 'VIRTUAL' },
  { nome: 'XDC Network', ticker: 'XDC' },
  { nome: 'Optimism', ticker: 'OP' },
  { nome: 'Celestia', ticker: 'TIA' },
  { nome: 'PAX Gold', ticker: 'PAXG' },
  { nome: 'Sonic', ticker: 'S' },
  { nome: 'The Graph', ticker: 'GRT' },
  { nome: 'dogwifhat', ticker: 'WIF' },
  { nome: 'Immutable X', ticker: 'IMX' },
  { nome: 'Jito', ticker: 'JTO' },
  { nome: 'PancakeSwap', ticker: 'CAKE' },
  { nome: 'Floki Inu', ticker: 'FLOKI' },
  { nome: 'Curve', ticker: 'CRV' },
  { nome: 'Ethereum Name Service', ticker: 'ENS' },
  { nome: 'Aerodrome Finance', ticker: 'AERO' },
  { nome: 'Lido DAO Token', ticker: 'LDO' },
  { nome: 'JasmyCoin', ticker: 'JASMY' },
  { nome: 'Gala', ticker: 'GALA' },
  { nome: 'DeXe', ticker: 'DEXE' },
  { nome: 'The Sandbox', ticker: 'SAND' },
  { nome: 'BitTorrent', ticker: 'BTT' },
  { nome: 'Maple Finance', ticker: 'SYRUP' },
  { nome: 'Pyth Network', ticker: 'PYTH' },
  { nome: 'Pendle', ticker: 'PENDLE' },
  { nome: 'Tezos', ticker: 'XTZ' },
  { nome: 'Raydium', ticker: 'RAY' },
  { nome: 'Walrus', ticker: 'WAL' },
  { nome: 'Core', ticker: 'CORE' },
  { nome: 'MANA (Decentraland)', ticker: 'MANA' },
  { nome: 'Michi', ticker: 'MICHI' },
  { nome: 'THORChain', ticker: 'RUNE' },
  { nome: 'RippleUSD', ticker: 'RLUSD' },
  { nome: 'ApeCoin', ticker: 'APE' },
  { nome: 'ApeNFT', ticker: 'NFT' },
  { nome: 'Compound', ticker: 'COMP' },
  { nome: 'Kava', ticker: 'KAVA' },
  { nome: 'USDD', ticker: 'USDD' },
  { nome: 'Helium', ticker: 'HNT' },
  { nome: 'Morpho', ticker: 'MORPHO' },
  { nome: 'Starknet', ticker: 'STRK' },
  { nome: 'Dog (Bitcoin)', ticker: 'DOG' },
  { nome: 'Reserve Rights', ticker: 'RSR' },
  { nome: 'dYdX', ticker: 'DYDX' },
  { nome: 'Kaito', ticker: 'KAITO' },
  { nome: 'SuperVerse', ticker: 'SUPER' },
  { nome: 'MultiversX', ticker: 'EGLD' },
  { nome: 'Mog Coin', ticker: 'MOG' },
  { nome: 'Aioz', ticker: 'AIOZ' },
  { nome: 'Axie Infinity Shard', ticker: 'AXS' },
  { nome: 'Ether.fi', ticker: 'ETHFI' },
  { nome: 'JUST', ticker: 'JST' },
  { nome: 'Chiliz', ticker: 'CHZ' },
  { nome: 'Eigenlayer', ticker: 'EIGEN' },
  { nome: 'Sun Token', ticker: 'SUN' },
  { nome: 'Wormhole', ticker: 'W' },
  { nome: 'Arweave', ticker: 'AR' },
  { nome: 'Axelar', ticker: 'AXL' },
  { nome: 'ZKsync', ticker: 'ZK' },
  { nome: 'Maker DAO', ticker: 'MKR' },
  { nome: 'Ronin', ticker: 'RON' },
  { nome: 'Gnosis', ticker: 'GNO' },
  { nome: 'Amp', ticker: 'AMP' },
  { nome: 'Popcat', ticker: 'POPCAT' },
  { nome: 'Aethir', ticker: 'ATH' },
  { nome: 'Beam', ticker: 'BEAM' },
  { nome: 'Livepeer', ticker: 'LPT' },
  { nome: 'Grass', ticker: 'GRASS' },
  { nome: 'Akash', ticker: 'AKT' },
  { nome: 'Turbo', ticker: 'TURBO' },
  { nome: '1Inch', ticker: '1INCH' },
  { nome: 'Safe', ticker: 'SAFE' },
  { nome: 'Moca Coin', ticker: 'MOCA' },
  { nome: 'Cat in dogs world', ticker: 'MEW' },
  { nome: 'Convex Finance', ticker: 'CVX' },
  { nome: 'Golem', ticker: 'GLM' },
  { nome: 'LayerZero', ticker: 'ZRO' },
  { nome: 'EURC', ticker: 'EURC' },
  { nome: 'Peanut the Squirrel', ticker: 'PNUT' },
  { nome: 'Mina', ticker: 'MINA' },
  { nome: 'Kusama', ticker: 'KSM' },
  { nome: 'Berachain', ticker: 'BERA' },
  { nome: 'Frax Share', ticker: 'FXS' },
  { nome: 'Mantra', ticker: 'OM' },
  { nome: 'IoTeX', ticker: 'IOTX' },
  { nome: 'Synthetix', ticker: 'SNX' },
  { nome: 'Basic Attention Token', ticker: 'BAT' },
  { nome: 'Oasis Network', ticker: 'ROSE' },
  { nome: '0x', ticker: 'ZRX' },
  { nome: 'Astar', ticker: 'ASTR' },
  { nome: 'Notcoin', ticker: 'NOT' },
  { nome: 'Wemix', ticker: 'WEMIX' },
  { nome: 'yearn.finance', ticker: 'YFI' },
  { nome: 'Blur', ticker: 'BLUR' },
  { nome: 'Melania Meme', ticker: 'MELANIA' },
  { nome: 'SushiSwap', ticker: 'SUSHI' },
  { nome: 'EOS', ticker: 'EOS' },
  { nome: 'Zetachain', ticker: 'ZETA' },
  { nome: 'Origin Trail', ticker: 'TRAC' },
  { nome: 'ai16z', ticker: 'AI16Z' },
  { nome: 'Liquity', ticker: 'LQTY' },
  { nome: 'Neiro on ETH', ticker: 'NEIRO' },
  { nome: 'Gigachad', ticker: 'GIGA' },
  { nome: 'Celo', ticker: 'CELO' },
  { nome: 'Holo', ticker: 'HOT' },
  { nome: 'ANKR', ticker: 'ANKR' },
  { nome: 'Moo Deng', ticker: 'MOODENG' },
  { nome: 'GMX', ticker: 'GMX' },
  { nome: 'Cow Protocol', ticker: 'COW' },
  { nome: 'Solayer', ticker: 'LAYER' },
  { nome: 'Kamino', ticker: 'KMNO' },
  { nome: 'STEPN', ticker: 'GMT' },
  { nome: 'Launch Coin', ticker: 'LAUNCHCOIN' },
  { nome: 'Enjin', ticker: 'ENJ' },
  { nome: 'aixbt by Virtuals', ticker: 'AIXBT' },
  { nome: 'Mask Network', ticker: 'MASK' },
  { nome: 'io.net', ticker: 'IO' },
  { nome: 'Orca', ticker: 'ORCA' },
  { nome: 'Request', ticker: 'REQ' },
  { nome: 'COTI', ticker: 'COTI' },
  { nome: 'SKALE Network', ticker: 'SKL' },
  { nome: 'Magic Eden', ticker: 'ME' },
  { nome: 'Rocket Pool', ticker: 'RPL' },
  { nome: 'Osmosis', ticker: 'OSMO' },
  { nome: 'MetisDAO', ticker: 'METIS' },
  { nome: 'Space and Time', ticker: 'SXT' },
  { nome: 'Book of Meme', ticker: 'BOME' },
  { nome: 'Arkham', ticker: 'ARKM' },
  { nome: 'Loopring', ticker: 'LRC' },
  { nome: 'Storj', ticker: 'STORJ' },
  { nome: 'Tellor', ticker: 'TRB' },
  { nome: 'Mythos', ticker: 'MYTH' },
  { nome: 'AltLayer', ticker: 'ALT' },
  { nome: 'UMA', ticker: 'UMA' },
  { nome: 'Goatseus Maximus', ticker: 'GOAT' },
  { nome: 'Pixels', ticker: 'PIXEL' },
  { nome: 'Venice Token', ticker: 'VVV' },
  { nome: 'Band Protocol', ticker: 'BAND' },
  { nome: 'SSV Network', ticker: 'SSV' },
  { nome: 'Civic', ticker: 'CVC' },
  { nome: 'ConstitutionDAO', ticker: 'PEOPLE' },
  { nome: 'Metaplex', ticker: 'MPLX' },
  { nome: 'Cookie DAO', ticker: 'COOKIE' },
  { nome: 'Biconomy', ticker: 'BICO' },
  { nome: 'Power Ledger', ticker: 'POWR' },
  { nome: 'Keep Network', ticker: 'KEEP' },
  { nome: 'Redstone', ticker: 'RED' },
  { nome: 'Blast', ticker: 'BLAST' },
  { nome: 'Echelon Prime', ticker: 'PRIME' },
  { nome: 'Hivemapper', ticker: 'HONEY' },
  { nome: 'Hashflow', ticker: 'HFT' },
  { nome: 'Yield Guild Games', ticker: 'YGG' },
  { nome: 'Act I The AI Prophecy', ticker: 'ACT' },
  { nome: 'Polygon', ticker: 'MATIC' },
  { nome: 'Audius', ticker: 'AUDIO' },
  { nome: 'Aevo', ticker: 'AEVO' },
  { nome: 'Memecoin', ticker: 'MEME' },
  { nome: 'Carv', ticker: 'CARV' },
  { nome: 'Pax Dollar', ticker: 'USDP' },
  { nome: 'BANCOR', ticker: 'BNT' },
  { nome: 'iExec RLC', ticker: 'RLC' },
  { nome: 'Balancer', ticker: 'BAL' },
  { nome: 'Avail', ticker: 'AVAIL' },
  { nome: 'Delysium', ticker: 'AGI' },
  { nome: 'Illuvium', ticker: 'ILV' },
  { nome: 'Goldfinch', ticker: 'GFI' },
  { nome: 'Numeraire', ticker: 'NMR' },
  { nome: 'Kyber Network', ticker: 'KNC' },
  { nome: 'Braintrust', ticker: 'BTRST' },
  { nome: 'Saga', ticker: 'SAGA' },
  { nome: 'Simons Cat', ticker: 'CAT' },
  { nome: 'Celer Network', ticker: 'CELR' },
  { nome: 'Cyber', ticker: 'CYBER' },
  { nome: 'Open Campus', ticker: 'EDU' },
  { nome: 'Sundog', ticker: 'SUNDOG' },
  { nome: 'Omni Network', ticker: 'OMNI' },
  { nome: 'Bounce', ticker: 'AUCTION' },
  { nome: 'API3', ticker: 'API3' },
  { nome: 'Orchid', ticker: 'OXT' },
  { nome: 'DeFi Pulse Index', ticker: 'DPI' },
  { nome: 'Bounce Bit', ticker: 'BB' },
  { nome: 'Bubblemaps', ticker: 'BMT' },
  { nome: 'Cartesi', ticker: 'CTSI' },
  { nome: 'Just a chill guy', ticker: 'CHILLGUY' },
  { nome: 'Gods Unchained', ticker: 'GODS' },
  { nome: 'WINkLink', ticker: 'WIN' },
  { nome: 'Scroll', ticker: 'SCR' },
  { nome: 'Realio', ticker: 'RIO' },
  { nome: 'Autonolas', ticker: 'OLAS' },
  { nome: 'DIA', ticker: 'DIA' },
  { nome: 'Smooth Love Potion', ticker: 'SLP' },
  { nome: 'Tensor', ticker: 'TNSR' },
  { nome: 'SuperRare', ticker: 'RARE' },
  { nome: 'Fwog', ticker: 'FWOG' },
  { nome: 'Griffain', ticker: 'GRIFFAIN' },
  { nome: 'Highstreet', ticker: 'HIGH' },
  { nome: 'MyNeighborAlice', ticker: 'ALICE' },
  { nome: 'Origin Protocol', ticker: 'OGN' },
  { nome: 'TrueFi', ticker: 'TRU' },
  { nome: 'Slerf', ticker: 'SLERF' },
  { nome: 'Zeta', ticker: 'ZEX' },
  { nome: 'Radicle', ticker: 'RAD' },
  { nome: 'Stargate Finance', ticker: 'STG' },
  { nome: 'FLOCK', ticker: 'FLOCK' },
  { nome: 'Vine', ticker: 'VINE' },
  { nome: 'zerebro', ticker: 'ZEREBRO' },
  { nome: 'eUSD', ticker: 'EUSD' },
  { nome: 'AI Rig Complex', ticker: 'ARC' },
  { nome: 'Omg Network', ticker: 'OMG' },
  { nome: 'Parcl', ticker: 'PRCL' },
  { nome: 'Helium Mobile', ticker: 'MOBILE' },
  { nome: 'Clover Finance', ticker: 'CLV' },
  { nome: 'Dusk', ticker: 'DUSK' },
  { nome: 'Renzo', ticker: 'REZ' },
  { nome: 'Alien Worlds', ticker: 'TLM' },
  { nome: 'DAO Maker', ticker: 'DAO' },
  { nome: 'Radio Caca', ticker: 'RACA' },
  { nome: 'PlatON', ticker: 'LAT' },
  { nome: 'Green Satoshi Token', ticker: 'GST' },
  { nome: 'Stader', ticker: 'SD' },
  { nome: 'Badger DAO', ticker: 'BADGER' },
  { nome: 'Wen', ticker: 'WEN' },
  { nome: 'Adshares', ticker: 'ADS' },
  { nome: 'ZUSD', ticker: 'ZUSD' },
  { nome: 'Aavegotchi', ticker: 'GHST' },
  { nome: 'Swell', ticker: 'SWELL' },
  { nome: 'Polkastarter', ticker: 'POLS' },
  { nome: 'Alchemix', ticker: 'ALCX' },
  { nome: 'Hifi Finance', ticker: 'HIFI' },
  { nome: 'EverValue', ticker: 'EVA' },
  { nome: 'Rarible', ticker: 'RARI' },
  { nome: 'AS Roma Fan Token', ticker: 'ASRFT' },
  { nome: 'OG', ticker: 'OGFT' },
  { nome: 'Harvest Finance', ticker: 'FARM' },
  { nome: 'Star Atlas', ticker: 'ATLAS' },
  { nome: 'Synapse', ticker: 'SYN' },
  { nome: 'Sweat Economy', ticker: 'SWEAT' },
  { nome: 'Bluzelle', ticker: 'BLZ' },
  { nome: 'Perpetual Protocol', ticker: 'PERP' },
  { nome: 'GYEN', ticker: 'GYEN' },
  { nome: 'Shadow Token', ticker: 'SHDW' },
  { nome: 'Star Atlas DAO', ticker: 'POLIS' },
  { nome: 'Paris Saint-Germain Fan Token', ticker: 'PSGFT' },
  { nome: 'Stella', ticker: 'ALPHA' },
  { nome: 'Pirate', ticker: 'PIRATE' },
  { nome: 'LooksRare', ticker: 'LOOKS' },
  { nome: 'Barcelona Fan Token', ticker: 'BARFT' },
  { nome: 'Galatasaray Fan Token', ticker: 'GALFT' },
  { nome: 'Galxe', ticker: 'GAL' },
  { nome: 'Spectral', ticker: 'SPEC' },
  { nome: 'BasedAI', ticker: 'BASEDAI' },
  { nome: 'Marinade', ticker: 'MNDE' },
  { nome: 'Juventus Fan Token', ticker: 'JUVFT' },
  { nome: 'Ren', ticker: 'REN' },
  { nome: 'AllianceBlock Nexera', ticker: 'NXRA' },
  { nome: 'CEEK VR', ticker: 'CEEK' },
  { nome: 'Manchester City', ticker: 'CITYFT' },
  { nome: 'Mother Iggy', ticker: 'MOTHER' },
  { nome: 'Opulous', ticker: 'OPUL' },
  { nome: 'Aurory', ticker: 'AURY' },
  { nome: 'CorgiAI', ticker: 'CORGIAI' },
  { nome: 'Atletico De Madrid Fan Token', ticker: 'ATMFT' },
  { nome: 'Agridex', ticker: 'AGRI' },
  { nome: 'Rally', ticker: 'RLY' },
  { nome: 'AC Milan', ticker: 'ACMFT' },
  { nome: 'Associação de Futebol Argentina', ticker: 'ARGFT' },
  { nome: 'Ethervista', ticker: 'VISTA' },
  { nome: 'Wayfinder', ticker: 'PROMPT' },
  { nome: 'Happycat', ticker: 'HAPPY' },
  { nome: 'Inter Milan FT', ticker: 'INTERFT' },
  { nome: 'Natus Vincere', ticker: 'NAVIFT' },
  { nome: 'Rootstock Smart Bitcoin', ticker: 'RBTC' },
  { nome: 'SingularityDAO', ticker: 'SDAO' },
  { nome: 'Portugal National Team FT', ticker: 'PORFT' },
  { nome: 'Colb USD', ticker: 'USC' },
  { nome: 'PlayDapp', ticker: 'PDA' },
  { nome: 'Keep3rV1', ticker: 'KP3R' },
  { nome: 'Whales Market', ticker: 'WHALES' },
  { nome: 'Flamengo', ticker: 'MENGOFT' },
  { nome: 'Team Alliance', ticker: 'ALLFT' },
  { nome: 'Sky Dollar', ticker: 'USDS' },
  { nome: 'Nodle', ticker: 'NODL' },
  { nome: 'BSC Young Boys', ticker: 'YBOFT' },
  { nome: 'Dynasty', ticker: 'DYN' },
  { nome: 'BVM Network', ticker: 'BVM' },
  { nome: 'Aston Martin Cognizant', ticker: 'AMFT' },
  { nome: 'Alfa Romeo Racing', ticker: 'SAUBERFT' },
  { nome: '$SAL', ticker: 'SAL' },
  { nome: 'Professional Fighters League', ticker: 'PFLFT' },
  { nome: 'WiBX', ticker: 'WBX' },
  { nome: 'Team Heretics', ticker: 'THFT' },
  { nome: 'Ribus', ticker: 'RIB' },
  { nome: 'Sint-Truidense FT', ticker: 'STVFT' },
  { nome: 'Decentral Games', ticker: 'DG' },
  { nome: 'BRL 1', ticker: 'BRL1' },
  { nome: 'Independiente Fan Token', ticker: 'CAIFT' },
  { nome: 'Corinthians', ticker: 'SCCPFT' },
  { nome: 'SPFC', ticker: 'SPFCFT' },
  { nome: 'Esporte Clube Bahia Fan Token', ticker: 'BAHIAFT' },
  { nome: 'Clube Atlético Mineiro', ticker: 'GALOFT' },
  { nome: 'De.Fi', ticker: 'DEFI' },
  { nome: 'Moss Carbon Credit', ticker: 'MCO2' },
  { nome: 'Vasco da Gama Fan Token', ticker: 'VASCOFT' },
  { nome: 'UFC FT', ticker: 'UFCFT' },
  { nome: 'BT Token Black 05', ticker: 'BTB05' },
  { nome: 'Metaverse Index', ticker: 'MVI' },
  { nome: 'Neiro', ticker: 'NEIROCTO' },
  { nome: 'eGBP', ticker: 'EGBP' },
  { nome: 'SC Internacional Fan Token', ticker: 'SACIFT' },
  { nome: 'VinoCoin', ticker: 'VINO' },
  { nome: 'Fluminense FC Fan Token', ticker: 'FLUFT' },
  { nome: 'Ambify', ticker: 'ABFY' },
  { nome: 'VERDAO', ticker: 'VERDAOFT' },
  { nome: 'eEUR', ticker: 'EEUR' },
  { nome: 'Drift Protocol', ticker: 'DRIFT' },
  { nome: 'KannaCoin', ticker: 'KNN' },
  { nome: 'Prime Token', ticker: 'PRT' },
  { nome: 'Bluebell', ticker: 'BBLL' },
];
